baseurl = "https://tonini.dev"
defaultContentLanguage = "en"
hasCJKLanguage = false
paginate = 4
theme = "hugo-theme-texify"
title = "Francesco Tonini"

googleAnalytics = "UA-84358665-4"
pygmentsUseClasses = true

[author]
name = "Francesco Tonini"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "post"
  name = "Post"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/post/"
  weight = 2
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3

[params]
  custom_css = ["css/main.css"]
  description = "Student by day, developer by night. In love with AI and IoT. Co-founder of BotFactory.y"
  enable_mathjax = false
  footnote = "Follow me on <a class=link href=https://github.com/francescotonini>GitHub</a> or <a class=link href=https://twitter.com/toninifrancesco>Twitter</a> | <a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed target=_blank rel=noopener>CC BY-NC-SA 4.0</a>"
  keywords = ["blog", "thoughts", "achievements", "developer", "student", "ai", "iot", "ios", "android", "app", "csharp", "c", "c++", "nodejs",
              "dotnet", "windowsphone", "windows", "deeplearning", "machinelearning", "trackbot", "pricetrackbot", "botfactory", "botfactoryit", "javascript",
              "linux", "telegram", "apple", "univraule", "univrorari", "bot", "unitn", "univr"]
