baseurl = "https://www.tonini.dev"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Francesco Tonini"
title = "Francesco Tonini"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = ""
googleAnalytics = "UA-84358665-4"
enableRobotsTXT = true

## Site Settings
[params]
author = "Francesco Tonini"
intro = "CS Student"
description = "Student by day, developer by night. Co-founder <a href=\"https://botfactory.it/\">@BotFactory</a>. In love with AI."
authorimage = "me.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Thoughts, achievements, dev and F1 stuff."
keywords = "blog,thoughts,achievements,dev,developer,app,android,ios,ai,deeplearning,f1,formula1,ferrari"

## Social Accounts
[params.social]
github = "francescotonini"
linkedin = "toninifrancesco"
twitter = "toninifrancesco"

## Extras
[params.extra]
copyright = "© 2019. Francesco Tonini. [All Rights Reserved](https://creativecommons.org/licenses/by-nc-nd/3.0/legalcode)."
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
[[menu.main]]
    name = "posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
