baseurl = "https://tonini.dev"
languagecode = "en-US"
paginate = 4
theme = "hugo-coder"
title = "Francesco Tonini"
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm"]

googleAnalytics = "UA-84358665-4"

[params]
  author = "Francesco Tonini"
  description = "Student by day, developer at night! MSc in Computer Science @ UniTrento. In love with AI and coffee." 
  footercontent = "<i>I'm not superstitious, but I'm a little 'stitious.</i>"
  avatarUrl = "/profile.jpg"
  favicon_32 = "/favicon-32x32.png"
  favicon_16 = "/favicon-16x16.png"
  touchIcon = "/apple-touch-icon.png"
  since = 1997
  colorScheme = "auto"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/francescotonini/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter"
  weight = 2
  url = "https://twitter.com/toninifrancesco/"
[[params.social]]
  name = "Blog"
  icon = "fa fa-globe"
  weight = 3
  url = "https://francescotti.com"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/toninifrancesco/"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "https://francescotti.com"

[[menu.main]]
  name = "About"
  weight = 2
  url = "/about"